### ISSUE TITLE
Use the correct units in benchmarks

### ISSUE THREAD

**Issue by DhairyaLGandhi** [nirmal-suthar/Flux3D.jl#13]

**Comment by nirmal-suthar** [comment]
I didn't get your comment, should I use seconds instead of milliseconds?

**Comment by DhairyaLGandhi** [comment]
0.x ms suggests you probably want to report the time from `@btime` in microseconds.

All the benchmarks don't need to follow the same units as long as you use the same ones for each test in flux3d and kaolin

**Comment by DhairyaLGandhi** [comment]
I don't think this is reflected in the readme, and you missed the graphs I think

**Comment by nirmal-suthar** [comment]
I have updated readme on master branch.

**Comment by DhairyaLGandhi** [comment]
Compose => Chain in the plots?

**Comment by DhairyaLGandhi** [comment]
@nirmal-suthar ^

**Comment by nirmal-suthar** [comment]
Updated
